### ISSUE TITLE
[BUG] Examples are not working in CodeSandbox

### ISSUE THREAD

**Issue by astec** [TinkoffCreditSystems/ng-polymorpheus#26]
# 🐞 Bug report

### Description

URL: https://codesandbox.io/s/github/TinkoffCreditSystems/ng-polymorpheus/tree/master/projects/demo
Shows:
```
Something went wrong
API rate limit exceeded for app ID c07a89833b557afc7be2.
```

### Reproduction

From [README.md](https://github.com/TinkoffCreditSystems/ng-polymorpheus/blob/master/README.md) follow a link to https://codesandbox.io/s/github/TinkoffCreditSystems/ng-polymorpheus/tree/master/projects/demo

### Expected behavior

To see a working example.

### Versions
 - Browser - any

### Additional context

No additional context required.

**Comment by waterplea** [comment]
Looks like it's working now. Perhaps there were too many visits at some point?
